version: '2.1'
services:
  neurondb:
    image: neuronesbperegrineconnect/neurondb:3.7.5.100
    environment:
      sa_password: "Password123"
      HOSTNAME: neurondb
      ACCEPT_EULA: "Y"
    volumes:
      - C:\Users\steve.kardian\Documents\Neuron ESB 3\Business Process to Workflow Sample\docker\dbFiles:C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\Data
    ports:
      - "1433:1433"
  business process to workflow sample:
    image: neuronesbperegrineconnect/neuronesb:3.7.5.100_{serverVersionTag}
    entrypoint: /app/ESBService.exe
    env_file: config.env
    environment:
      controlPort: 50004
      HOSTNAME: business process to workflow sample
    depends_on:
      - "neurondb"
    volumes:
      - C:\Users\steve.kardian\Documents\Neuron ESB 3\Business Process to Workflow Sample:C:\Users\steve.kardian\Documents\Neuron ESB 3\Business Process to Workflow Sample
    ports:
      - 50000:50000
      - 50010-50100:50010-50100
      - 50004:50004
      - 50002:50002
      - 50200:50200
      - 51003:51003
  
    hostname: business process to workflow sample
  #-{NeuronEndpointHostTemplate}
networks:
  default:
    external:
      name: nat